### PR TITLE
added a basic testimonial card 

### PR DESCRIPTION
**Pull request by yashsarnaik22**
removed the previous card from card directory and added new basic testimonial card in the testimonial directory.
also added a folder for images used for the cards in the same directory.

### CODE REVIEW

**Comment by rupsha014** [comment]
@yashsarnaik22 just add the main code ....no need to add the html boiler plate and also just add one file only...there is no need of changing the readme or other files

**Comment by yashsarnaik22** [comment]
@rupsha014 when I do  'git push' all the files get pushed and then I open a PR for the contribution.
Is there any other way around?

**Comment by yashsarnaik22** [comment]
Sorry for the README.md file changes. I was just reading it and it had some typos, so I just corrected them. I did no other changes to it.
@Rajdip019

**Comment by yashsarnaik22** [comment]
I'll generate a new PR and close this one.

**Pull request closed without merging**
