### PR TITLE
Footer-black4 created using tailwind css.

### PR DESCRIPTION
**Pull request by yashsarnaik22**
- used icon from fontawesome.
- only footer component code is present in file without html boilerplate
- cdn link to fontawesome and tailwind css are provided in the start of file
- couldn't find the color code for desired background-color
- couldn't find 'LIFT' logo
- 
image

### CODE REVIEW

**Comment by Rajdip019** [comment]
Can you replace the. fontawesome icons to heroicons? @yashsarnaik22

**Comment by yashsarnaik22** [comment]
sure @Rajdip019

**Comment by yashsarnaik22** [comment]
@Rajdip019 but the SVG links for icons are too big and I will have to edit the whole code. 
also the icons are not inline blocks so it changes the alignment and indentation.

Can we go with the fontawesome icon?

**Comment by Rajdip019** [comment]
Inside the SVG component give className and setup the width that will be it.

**Comment by yashsarnaik22** [comment]
Okay will try.

**Comment by yashsarnaik22** [comment]
@Rajdip019 I have changed the location, phone and fax icon from fontawesome to heroicons.

But heroicons do not have icons for social medias (facebook, twitter, linkedin, youtube, pintrest, google+).
what you want me to do?

**Comment by Rajdip019** [comment]
We can have fontawesome icons for them as of now. @yashsarnaik22

**Comment by yashsarnaik22** [comment]
Okay, so do I have to create a new PR?

**Comment by Rajdip019** [comment]
No, you can update this PR. @yashsarnaik22

**Comment by yashsarnaik22** [comment]
Pushed! @Rajdip019 please check.

**Comment by Rajdip019** [comment]
Good job @yashsarnaik22 

Congrats 🎉, your PR got merged. To be eligible for the swags from ClueLess. Follow this steps.

1. Star this repository. ⭐
2. SignIn / SignUp in [[ClueLess Website](https://www.clueless.tech/)](https://www.clueless.tech/) .
3. Go to profile section from the top right hand corner.



1. Comment your profile URL under this comment tagging the person who merged your PR.

That’s it. Follow the leaderboard !

And don’t forget to share your achievement with your friends.

**Comment by yashsarnaik22** [comment]
https://www.clueless.tech/profile/admin/86489787 @Rajdip019

**Pull request merged**
