### PR TITLE
Centered-search-navbar

### PR DESCRIPTION
**Pull request by souraOP**
Here is the component I have built:
Centered search navbar having the leftmost side the navbar title and three links on the rightmost side.

Here is a screenshot link of that component

https://ibb.co/Wt0kRgL
https://ibb.co/3v4j9qy

### CODE REVIEW

**Comment by Rajdip019** [comment]
Hey @souraOP can you give a screenshot of where is this Navbar in the Figma file.

**Comment by souraOP** [comment]
> Hey @souraOP can you give a screenshot of where is this Navbar in the Figma file.

Hey @Rajdip019 I didn't used Figma here, I screenshot it from Tailwind Play preview window.

**Comment by Rajdip019** [comment]
Hey, we are trying to make a UI library which follows a same design system, not like anyone can make a UI component and dump it here. Please refer to #29 Issue to know more.

**Comment by souraOP** [comment]
> Hey, we are trying to make a UI library which follows a same design system, not like anyone can make a UI component and dump it here. Please refer to #29 Issue to know more. @souraOP

Okay, I got it. Thanks for the refer @Rajdip019

**Comment by Rajdip019** [comment]
Closing this PR for now you can make a component from there make a Issue of that and then raise a PR. @souraOP

**Pull request closed without merging**
