### PR TITLE
Create dropdown-3.html

### PR DESCRIPTION
**Pull request by nik132-eng**
https://play.tailwindcss.com/n18jaRm4Jv?layout=horizontal

image

PR : #766

### CODE REVIEW

**Comment by RavindraP04** [comment]
This thing is already available in dropdown-2.html @nik132-eng

**Comment by Rajdip019** [comment]
Can we make the dropdown work? @nik132-eng

**Comment by nik132-eng** [comment]
I will try to do it in morning

**Comment by nik132-eng** [comment]
Sorry I searched But couldn't find any artical or blog for any working in tailwind play enviroment.

reason behind is that we have to build logic and that is not possible in html only. ( my point of view )

here is one working dropdown : https://play.tailwindcss.com/csDLkZCBZD

**Comment by Rajdip019** [comment]
This one looks great I guess. Just need to add the stylings according to the design system. @nik132-eng

**Comment by Rajdip019** [comment]
But it is not working. @nik132-eng

**Comment by nik132-eng** [comment]
I tried but facing issues with implementing

**Comment by Rajdip019** [comment]
The previous one without designs on was working take reference from that. @nik132-eng

**Comment by Rajdip019** [comment]
Sure, help @nik132-eng as well.

**Comment by RavindraP04** [comment]
@nik132-eng Firstly, It is possible to make this work without js, you can use [group](https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-parent-state) in tailwind to dropdown on hover, You need to write `group` in parent div and then use `group-hover:block` By this way you can dropdown for once only, then I search more and found out that you can also choose which child element to make  changes, when you hover on it, For this you need to name the parent group like for the first dropdown, you can use `group/first` [here instead of first you can give any other name too] then add `group-hover/first:block` & `hidden`, Then for the second dropdown you can use `group/second` and then in the child div use  `group-hover/first:block` & `hidden`, 
See the [**code for this dropdown**](https://play.tailwindcss.com/dAtKJzXNUL?layout=horizontal) and then you will understand it better,
**_If you have any issue do let me know, otherwise make changes in the code and update the commit_**
Also if you want to do this in HTML & core CSS the refer to the [this article](https://phppot.com/css/multilevel-dropdown-menu-with-pure-css/) 

> Sorry I searched But couldn't find any artical or blog for any working in tailwind play enviroment.
> 
> reason behind is that we have to build logic and that is not possible in html only. ( my point of view )
> 
> here is one working dropdown : https://play.tailwindcss.com/csDLkZCBZD

**Comment by RavindraP04** [comment]
> Sure, help @nik132-eng as well.

@Rajdip019 Checkout [this](https://play.tailwindcss.com/dAtKJzXNUL?layout=horizontal)

**Comment by Rajdip019** [comment]
@RavindraP04 make a new PR. Otherwise the points will be given to @nik132-eng

**Pull request merged**
