### PR TITLE
Added success rounded white

### LINKED ISSUE #1997: Create success rounded white
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
small
image

large
image

After building the component please raise a PR with a screenshot of the component and add the component in `Form/src/success-rounded-white.html`

You can also check the design in [figma](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=9lrAGBHDcSPa4kGk-0)
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

### PR DESCRIPTION
**Pull request by AshutoshSingh2021**
#Description

Added the success rounded white.

Fixes #1997 

Screenshot (193)

### CODE REVIEW

**Comment by AshutoshSingh2021** [comment]
@RavindraP04 I have added success rounded white, please review my PR.

**Comment by RavindraP04** [comment]
@AshutoshSingh2021 Can you make it of flexible width, I mean don't give fixed width, just give mx-10 so that it will look responsive

**Comment by AshutoshSingh2021** [comment]
@RavindraP04 I changed the width please have a look if it's fixed

Screenshot (194)

**Comment by AshutoshSingh2021** [comment]
should I make the PR with this change?

**Comment by RavindraP04** [comment]
> should I make the PR with this change?

@AshutoshSingh2021  Yes

**Comment by RavindraP04** [comment]
Congrats @AshutoshSingh2021 🎉, your PR got merged. To be eligible for the swags from ClueLess.

Don’t forget to star this repository. ⭐

**Pull request merged**
