### PR TITLE
Created form-email-form.html

### PR DESCRIPTION
**Pull request by animesh156**
Created email form component using HTML5 & Tailwind CSS
here's the screenshot of the component
Screenshot (91)

### CODE REVIEW

**Comment by Rajdip019** [comment]
The form tag started but never ended. @animesh156

**Comment by animesh156** [comment]
@Rajdip019  corrected my mistake

**Comment by Rajdip019** [comment]
Good job @animesh156 

Congrats 🎉, your PR got merged. To be eligible for the swags from ClueLess. Follow this steps.

1. Star this repository. ⭐
2. SignIn / SignUp in [[ClueLess Website](https://www.clueless.tech/)](https://www.clueless.tech/) .
3. Go to profile section from the top right hand corner.



1. Comment your profile URL under this comment tagging the person who merged your PR.

That’s it. Follow the leaderboard !

And don’t forget to share your achievement with your friends.

**Comment by animesh156** [comment]
profile/admin/114474707   thanks @Rajdip019 for merging my PR

**Pull request merged**
