### PR TITLE
Index

### PR DESCRIPTION
**Pull request by Hiresh23**

### CODE REVIEW

**Comment by Hiresh23** [comment]
Apple button made
Screenshot 2022-10-12 202214

**Comment by Rajdip019** [comment]
Please make a new PR this PR shows 1030+ file changes

**Comment by Rajdip019** [comment]
You just need to add this in a file, in proper path. @Hiresh23 

```
<button class="rounded-md bg-neutral-800 text-white w-64 h-24 cursor-pointer flex justify-center items-center"
    width="200px">
    <div class="pl-5">
        <div class=" rounded-full w-10 h-10 image" style="position: relative; right: 20px; bottom: 4px; " >
            <i class="fa-brands fa-apple object-cover fa-3x"></i>
        </div>
    </div>

    <div class="text" style="text-align:left; font-family:Poppins;">
        <div class="font-bold">Download on the</div>
        <div class="text-2xl">App Store</div>
    </div>

</button>
    <script src="https://kit.fontawesome.com/bf1edbf89d.js" crossorigin="anonymous"></script>
```

**Comment by Hiresh23** [comment]
i am creating push but it is showing access denied

**Comment by Rajdip019** [comment]
Closing this PR make a new PR. @Hiresh23

**Pull request closed without merging**
