### PR TITLE
Added Feature Card (medium outlined)

### PR DESCRIPTION
**Pull request by devjain2309**
Added feature card with medium outlined which consists of a user icon and more button.
Screenshot (34)

### CODE REVIEW

**Comment by Rajdip019** [comment]
Make the card width smaller as in the design. @devjain2309 

And please add this code

```
<div class="flex justify-center">
    <div class="block p-6 rounded-lg shadow-lg bg-white max-w-md">
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" color="blue" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
    <path stroke-linecap="round" stroke-linejoin="round" d="M15 19.128a9.38 9.38 0 002.625.372 9.337 9.337 0 004.121-.952 4.125 4.125 0 00-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 018.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0111.964-3.07M12 6.375a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zm8.25 2.25a2.625 2.625 0 11-5.25 0 2.625 2.625 0 015.25 0z" />
  </svg>
      <h4 class="text-gray-900 text-xl leading-tight font-medium mb-2">Lorem ipsum dolor sit amet consectetur adipisicing elit. </h4>
      <p class="text-gray-700 text-base mb-4">
       Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      </p>
      <button type="button" class="inline-block px-6 py-2 border-2 border-blue-400 text-blue-400 font-medium text-xs leading-tight rounded-full hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out">More ></button>
    </div>
  </div>
```
in the html file and there is no need to add the CSS file. Please remove the CSS file as well. @devjain2309

**Comment by devjain2309** [comment]
OK

**Review by devjain2309 — COMMENTED** [review]
UPDATED HTML FILE.

**Comment by Rajdip019** [comment]
No you just need to add that part only no css sheet. @devjain2309

**Comment by devjain2309** [comment]
Please check my PR

**Comment by Rajdip019** [comment]
Hey please don't add any HTML boiler template. @devjain2309 

Add only this code in the file and also we need some spacing as well.

```
  <div class="flex justify-center">
    <div class="block p-6 rounded-lg shadow-lg bg-white max-w-md">
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" color="blue" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
    <path stroke-linecap="round" stroke-linejoin="round" d="M15 19.128a9.38 9.38 0 002.625.372 9.337 9.337 0 004.121-.952 4.125 4.125 0 00-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 018.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0111.964-3.07M12 6.375a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zm8.25 2.25a2.625 2.625 0 11-5.25 0 2.625 2.625 0 015.25 0z" />
  </svg>
      <h4 class="text-gray-900 text-xl leading-tight font-medium mb-2">Lorem ipsum dolor sit amet consectetur adipisicing elit. </h4>
      <p class="text-gray-700 text-base mb-4">
       Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      </p>
      <button type="button" class="inline-block px-6 py-2 border-2 border-blue-400 text-blue-400 font-medium text-xs leading-tight rounded-full hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out">More ></button>
    </div>
  </div>
```

**Comment by Rajdip019** [comment]
Good job @devjain2309 

Congrats 🎉, your PR got merged. To be eligible for the swags from ClueLess. Follow this steps.

1. Star this repository. ⭐
2. SignIn / SignUp in [[ClueLess Website](https://www.clueless.tech/)](https://www.clueless.tech/) .
3. Go to profile section from the top right hand corner.

1. Comment your profile URL under this comment tagging the person who merged your PR.

That’s it. Follow the leaderboard !

And don’t forget to share your achievement with your friends.

**Comment by devjain2309** [comment]
https://www.clueless.tech/profile/admin/69387311
@Rajdip019

**Pull request merged**
