### PR TITLE
FEATURE: Create a Widget List-Item-6

### PR DESCRIPTION
**Pull request by Rancho2002**
Here is the component I have built.

Fix : #262 

Here is a screenshot of that.
image

### CODE REVIEW

**Comment by Rancho2002** [comment]
hi @Rajdip019 @rupsha014 take a review and merge it.

**Comment by Rancho2002** [comment]
Make sure you do the changes in tailwind.config.js as I have uploaded in my PR before review @rupsha014 , @Rajdip019

**Comment by Rajdip019** [comment]
Remove tailwind config.js and use blue-500 for color. Also if we click on the button the accordion does not open. Please fix them. @Rancho2002

**Comment by Rancho2002** [comment]
Hi @Rajdip019 , I checked twice the dropdown works well. For simplicity I have inserted the video demo. Look into it.

https://user-images.githubusercontent.com/92109154/197332731-afa9737e-f202-4099-b82e-4c03b06a4c49.mp4

**Comment by Rajdip019** [comment]
Yeah, I am saying on clicking the icon on the right it does not have any action. But we can go with this as well.

Good job @Rancho2002 

Congrats 🎉, your PR got merged. To be eligible for the swags from ClueLess. Follow this steps.

1. Star this repository. ⭐
2. SignIn / SignUp in [[ClueLess Website](https://www.clueless.tech/)](https://www.clueless.tech/) .
3. Go to profile section from the top right hand corner.



1. Comment your profile URL under this comment tagging the person who merged your PR.

That’s it. Follow the leaderboard !

And don’t forget to share your achievement with your friends.

**Pull request merged**
