### PR TITLE
Created form-search-large-form2

### PR DESCRIPTION
**Pull request by Upasana-Roy**
Created form-search-large-form2
Preview:
Screenshot (103)

### CODE REVIEW

**Comment by Rajdip019** [comment]
Text can not be seen. @Upasana-Roy  and make it perfect.

**Comment by Upasana-Roy** [comment]
@Rajdip019 Updated form-search-large-form2.html to match the requirements
preview:
Screenshot (105)

**Comment by Rajdip019** [comment]
Good job @Upasana-Roy 

Congrats 🎉, your PR got merged. To be eligible for the swags from ClueLess. Follow this steps.

1. Star this repository. ⭐
2. SignIn / SignUp in [[ClueLess Website](https://www.clueless.tech/)](https://www.clueless.tech/) .
3. Go to profile section from the top right hand corner.



1. Comment your profile URL under this comment tagging the person who merged your PR.

That’s it. Follow the leaderboard !

And don’t forget to share your achievement with your friends.

**Comment by Upasana-Roy** [comment]
@Rajdip019 Clueless Community Profile URL: https://www.clueless.tech/profile/admin/101974208252252381080

**Pull request merged**
