### PR TITLE
feature-card-image.html

### PR DESCRIPTION
**Pull request by hritikbhattacharya**
assigned issue#112

screenshot:

### CODE REVIEW

**Comment by hritikbhattacharya** [comment]
@Rajdip019 now check is it ok.

**Comment by hritikbhattacharya** [comment]
@Rajdip019 check this one updated the image as you have described

**Comment by Rajdip019** [comment]
Remove border @hritikbhattacharya

**Comment by hritikbhattacharya** [comment]
@Rajdip019 ok

**Comment by hritikbhattacharya** [comment]
@Rajdip019 now check.
screenshot after removing border: 
 
image

**Comment by hritikbhattacharya** [comment]
@Rajdip019 now review the PR

**Comment by Rajdip019** [comment]
LGTM.

Good job @hritikbhattacharya 

Congrats 🎉, your PR got merged. To be eligible for the swags from ClueLess. Follow this steps.

1. Star this repository. ⭐
2. SignIn / SignUp in [[ClueLess Website](https://www.clueless.tech/)](https://www.clueless.tech/) .
3. Go to profile section from the top right hand corner.

1. Comment your profile URL under this comment tagging the person who merged your PR.

That’s it. Follow the leaderboard !

And don’t forget to share your achievement with your friends.

**Pull request merged**
