### PR TITLE
Update feature-card-16.html

### PR DESCRIPTION
**Pull request by nik132-eng**
add hover effect and shadow

https://play.tailwindcss.com/PmjgrJbOyQ

image

### CODE REVIEW

**Comment by Rajdip019** [comment]
I guess for now we don't need a hover effect on this card. So closing this issue. No hover effect needed in the feature cards.

**Comment by nik132-eng** [comment]
> I guess for now we don't need a hover effect on this card. So closing this issue. No hover effect needed in the feature cards.

So Should I remove the hover effect and add more sizes?

**Comment by Rajdip019** [comment]
yeah you can do that I guess. @nik132-eng

**Comment by nik132-eng** [comment]
image
Is this ok?

**Comment by Rajdip019** [comment]
This looks great. @nik132-eng

**Pull request merged**
